from jinja2 import Template
from app.core import models
from datetime import datetime

REPORT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Case Report: {{ case.case_number }}</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 40px auto; padding: 20px; border: 1px solid #ddd; }
        h1 { color: #1e3a8a; border-bottom: 2px solid #1e3a8a; padding-bottom: 10px; }
        .metadata { background: #f3f4f6; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .section-title { font-size: 1.2em; font-weight: bold; margin-top: 30px; color: #1e3a8a; border-left: 4px solid #1e3a8a; padding-left: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f9fafb; }
        .status-badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 0.8em; font-weight: bold; }
        .status-verified { background: #dcfce7; color: #166534; }
        .status-conflict { background: #fee2e2; color: #991b1b; }
        .footer { margin-top: 50px; font-size: 0.8em; text-align: center; color: #6b7280; }
    </style>
</head>
<body>
    <h1>Veritas Legal Intelligence - Case Dossier</h1>
    
    <div class="metadata">
        <strong>Case:</strong> {{ case.title }} ({{ case.case_number }})<br>
        <strong>Firm:</strong> {{ case.firm.name }}<br>
        <strong>Generated:</strong> {{ now.strftime('%Y-%m-%d %H:%M:%S UTC') }}<br>
        <strong>Status:</strong> {{ case.status }}
    </div>

    <div class="section-title">Case Summary</div>
    <p>{{ case.description }}</p>

    <div class="section-title">Evidence List</div>
    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>Type</th>
                <th>Hash (SHA-256)</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for item in case.evidence %}
            <tr>
                <td>{{ item.title }}</td>
                <td>{{ item.type }}</td>
                <td style="font-family: monospace; font-size: 0.7em;">{{ item.file_hash[:16] }}...</td>
                <td>
                    <span class="status-badge {% if item.status == 'Verified' %}status-verified{% elif item.status == 'Conflict Detected' %}status-conflict{% endif %}">
                        {{ item.status }}
                    </span>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="section-title">AI Findings (XAI)</div>
    {% for report in xai_reports %}
    <div style="margin-top: 15px; padding: 10px; border: 1px dotted #ccc;">
        <strong>Subject:</strong> {{ report.summary }}<br>
        <ul>
            {% for claim in report.claims %}
            <li><strong>Claim:</strong> {{ claim.finding }} (Confidence: {{ (claim.confidence * 100)|round(1) }}%)</li>
            {% endfor %}
        </ul>
        {% if report.risk_flags %}
        <div style="color: #991b1b; font-weight: bold;">Flags:</div>
        <ul>
            {% for flag in report.risk_flags %}
            <li>{{ flag.message }} [{{ flag.severity }}]</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    {% else %}
    <p>No AI analysis findings available for this dossier.</p>
    {% endfor %}

    <div class="footer">
        This document was cryptographically generated by Veritas. Document Integrity ID: {{ case.id[:8] }}-{{ now.timestamp()|int }}
    </div>
</body>
</html>
"""

def generate_case_report(case: models.Case) -> str:
    template = Template(REPORT_TEMPLATE)
    
    # Extract XAI reports from case metadata
    metadata = case.metadata_fields or {}
    xai_reports = metadata.get("xai_reports", [])
    
    return template.render(
        case=case,
        xai_reports=xai_reports,
        now=datetime.utcnow()
    )
